// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the schedule client
type API interface {
	/*
	   GetSchedulePaused Get scheduler paused status*/
	GetSchedulePaused(ctx context.Context, params *GetSchedulePausedParams) (*GetSchedulePausedOK, error)
	/*
	   ListSchedules List schedules*/
	ListSchedules(ctx context.Context, params *ListSchedulesParams) (*ListSchedulesOK, error)
}

// New creates a new schedule API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for schedule API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetSchedulePaused Get scheduler paused status
*/
func (a *Client) GetSchedulePaused(ctx context.Context, params *GetSchedulePausedParams) (*GetSchedulePausedOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getSchedulePaused",
		Method:             "GET",
		PathPattern:        "/schedules/{job_type}/paused",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSchedulePausedReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSchedulePausedOK), nil

}

/*
ListSchedules List schedules
*/
func (a *Client) ListSchedules(ctx context.Context, params *ListSchedulesParams) (*ListSchedulesOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listSchedules",
		Method:             "GET",
		PathPattern:        "/schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSchedulesReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListSchedulesOK), nil

}
