// Code generated by go-swagger; DO NOT EDIT.

package chart_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteChartrepoRepoChartsNameVersionReader is a Reader for the DeleteChartrepoRepoChartsNameVersion structure.
type DeleteChartrepoRepoChartsNameVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteChartrepoRepoChartsNameVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteChartrepoRepoChartsNameVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteChartrepoRepoChartsNameVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteChartrepoRepoChartsNameVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteChartrepoRepoChartsNameVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteChartrepoRepoChartsNameVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteChartrepoRepoChartsNameVersionOK creates a DeleteChartrepoRepoChartsNameVersionOK with default headers values
func NewDeleteChartrepoRepoChartsNameVersionOK() *DeleteChartrepoRepoChartsNameVersionOK {
	return &DeleteChartrepoRepoChartsNameVersionOK{}
}

/*DeleteChartrepoRepoChartsNameVersionOK handles this case with default header values.

The specified chart entry is successfully deleted.
*/
type DeleteChartrepoRepoChartsNameVersionOK struct {
}

func (o *DeleteChartrepoRepoChartsNameVersionOK) Error() string {
	return fmt.Sprintf("[DELETE /chartrepo/{repo}/charts/{name}/{version}][%d] deleteChartrepoRepoChartsNameVersionOK ", 200)
}

func (o *DeleteChartrepoRepoChartsNameVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteChartrepoRepoChartsNameVersionUnauthorized creates a DeleteChartrepoRepoChartsNameVersionUnauthorized with default headers values
func NewDeleteChartrepoRepoChartsNameVersionUnauthorized() *DeleteChartrepoRepoChartsNameVersionUnauthorized {
	return &DeleteChartrepoRepoChartsNameVersionUnauthorized{}
}

/*DeleteChartrepoRepoChartsNameVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteChartrepoRepoChartsNameVersionUnauthorized struct {
}

func (o *DeleteChartrepoRepoChartsNameVersionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /chartrepo/{repo}/charts/{name}/{version}][%d] deleteChartrepoRepoChartsNameVersionUnauthorized ", 401)
}

func (o *DeleteChartrepoRepoChartsNameVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteChartrepoRepoChartsNameVersionForbidden creates a DeleteChartrepoRepoChartsNameVersionForbidden with default headers values
func NewDeleteChartrepoRepoChartsNameVersionForbidden() *DeleteChartrepoRepoChartsNameVersionForbidden {
	return &DeleteChartrepoRepoChartsNameVersionForbidden{}
}

/*DeleteChartrepoRepoChartsNameVersionForbidden handles this case with default header values.

Operation is forbidden or quota exceeded
*/
type DeleteChartrepoRepoChartsNameVersionForbidden struct {
}

func (o *DeleteChartrepoRepoChartsNameVersionForbidden) Error() string {
	return fmt.Sprintf("[DELETE /chartrepo/{repo}/charts/{name}/{version}][%d] deleteChartrepoRepoChartsNameVersionForbidden ", 403)
}

func (o *DeleteChartrepoRepoChartsNameVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteChartrepoRepoChartsNameVersionNotFound creates a DeleteChartrepoRepoChartsNameVersionNotFound with default headers values
func NewDeleteChartrepoRepoChartsNameVersionNotFound() *DeleteChartrepoRepoChartsNameVersionNotFound {
	return &DeleteChartrepoRepoChartsNameVersionNotFound{}
}

/*DeleteChartrepoRepoChartsNameVersionNotFound handles this case with default header values.

Not found
*/
type DeleteChartrepoRepoChartsNameVersionNotFound struct {
}

func (o *DeleteChartrepoRepoChartsNameVersionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /chartrepo/{repo}/charts/{name}/{version}][%d] deleteChartrepoRepoChartsNameVersionNotFound ", 404)
}

func (o *DeleteChartrepoRepoChartsNameVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteChartrepoRepoChartsNameVersionInternalServerError creates a DeleteChartrepoRepoChartsNameVersionInternalServerError with default headers values
func NewDeleteChartrepoRepoChartsNameVersionInternalServerError() *DeleteChartrepoRepoChartsNameVersionInternalServerError {
	return &DeleteChartrepoRepoChartsNameVersionInternalServerError{}
}

/*DeleteChartrepoRepoChartsNameVersionInternalServerError handles this case with default header values.

Internal server error occurred
*/
type DeleteChartrepoRepoChartsNameVersionInternalServerError struct {
}

func (o *DeleteChartrepoRepoChartsNameVersionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /chartrepo/{repo}/charts/{name}/{version}][%d] deleteChartrepoRepoChartsNameVersionInternalServerError ", 500)
}

func (o *DeleteChartrepoRepoChartsNameVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
