// Code generated by go-swagger; DO NOT EDIT.

package chart_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/goharbor/go-client/pkg/sdk/assist/models"
)

// GetChartrepoRepoChartsNameReader is a Reader for the GetChartrepoRepoChartsName structure.
type GetChartrepoRepoChartsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartrepoRepoChartsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetChartrepoRepoChartsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetChartrepoRepoChartsNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetChartrepoRepoChartsNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetChartrepoRepoChartsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetChartrepoRepoChartsNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetChartrepoRepoChartsNameOK creates a GetChartrepoRepoChartsNameOK with default headers values
func NewGetChartrepoRepoChartsNameOK() *GetChartrepoRepoChartsNameOK {
	return &GetChartrepoRepoChartsNameOK{}
}

/* GetChartrepoRepoChartsNameOK describes a response with status code 200, with default header values.

Retrieved all versions of the specified chart
*/
type GetChartrepoRepoChartsNameOK struct {
	Payload models.ChartVersions
}

func (o *GetChartrepoRepoChartsNameOK) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameOK  %+v", 200, o.Payload)
}
func (o *GetChartrepoRepoChartsNameOK) GetPayload() models.ChartVersions {
	return o.Payload
}

func (o *GetChartrepoRepoChartsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartrepoRepoChartsNameUnauthorized creates a GetChartrepoRepoChartsNameUnauthorized with default headers values
func NewGetChartrepoRepoChartsNameUnauthorized() *GetChartrepoRepoChartsNameUnauthorized {
	return &GetChartrepoRepoChartsNameUnauthorized{}
}

/* GetChartrepoRepoChartsNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetChartrepoRepoChartsNameUnauthorized struct {
}

func (o *GetChartrepoRepoChartsNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameUnauthorized ", 401)
}

func (o *GetChartrepoRepoChartsNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameForbidden creates a GetChartrepoRepoChartsNameForbidden with default headers values
func NewGetChartrepoRepoChartsNameForbidden() *GetChartrepoRepoChartsNameForbidden {
	return &GetChartrepoRepoChartsNameForbidden{}
}

/* GetChartrepoRepoChartsNameForbidden describes a response with status code 403, with default header values.

Operation is forbidden or quota exceeded
*/
type GetChartrepoRepoChartsNameForbidden struct {
}

func (o *GetChartrepoRepoChartsNameForbidden) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameForbidden ", 403)
}

func (o *GetChartrepoRepoChartsNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameNotFound creates a GetChartrepoRepoChartsNameNotFound with default headers values
func NewGetChartrepoRepoChartsNameNotFound() *GetChartrepoRepoChartsNameNotFound {
	return &GetChartrepoRepoChartsNameNotFound{}
}

/* GetChartrepoRepoChartsNameNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetChartrepoRepoChartsNameNotFound struct {
}

func (o *GetChartrepoRepoChartsNameNotFound) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameNotFound ", 404)
}

func (o *GetChartrepoRepoChartsNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameInternalServerError creates a GetChartrepoRepoChartsNameInternalServerError with default headers values
func NewGetChartrepoRepoChartsNameInternalServerError() *GetChartrepoRepoChartsNameInternalServerError {
	return &GetChartrepoRepoChartsNameInternalServerError{}
}

/* GetChartrepoRepoChartsNameInternalServerError describes a response with status code 500, with default header values.

Internal server error occurred
*/
type GetChartrepoRepoChartsNameInternalServerError struct {
}

func (o *GetChartrepoRepoChartsNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameInternalServerError ", 500)
}

func (o *GetChartrepoRepoChartsNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
