// Code generated by go-swagger; DO NOT EDIT.

package chart_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetChartrepoHealthReader is a Reader for the GetChartrepoHealth structure.
type GetChartrepoHealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartrepoHealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetChartrepoHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetChartrepoHealthUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetChartrepoHealthForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetChartrepoHealthOK creates a GetChartrepoHealthOK with default headers values
func NewGetChartrepoHealthOK() *GetChartrepoHealthOK {
	return &GetChartrepoHealthOK{}
}

/*GetChartrepoHealthOK handles this case with default header values.

Health status of chart repository service is returned.
*/
type GetChartrepoHealthOK struct {
	Payload *GetChartrepoHealthOKBody
}

func (o *GetChartrepoHealthOK) Error() string {
	return fmt.Sprintf("[GET /chartrepo/health][%d] getChartrepoHealthOK  %+v", 200, o.Payload)
}

func (o *GetChartrepoHealthOK) GetPayload() *GetChartrepoHealthOKBody {
	return o.Payload
}

func (o *GetChartrepoHealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetChartrepoHealthOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartrepoHealthUnauthorized creates a GetChartrepoHealthUnauthorized with default headers values
func NewGetChartrepoHealthUnauthorized() *GetChartrepoHealthUnauthorized {
	return &GetChartrepoHealthUnauthorized{}
}

/*GetChartrepoHealthUnauthorized handles this case with default header values.

Unauthorized
*/
type GetChartrepoHealthUnauthorized struct {
}

func (o *GetChartrepoHealthUnauthorized) Error() string {
	return fmt.Sprintf("[GET /chartrepo/health][%d] getChartrepoHealthUnauthorized ", 401)
}

func (o *GetChartrepoHealthUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoHealthForbidden creates a GetChartrepoHealthForbidden with default headers values
func NewGetChartrepoHealthForbidden() *GetChartrepoHealthForbidden {
	return &GetChartrepoHealthForbidden{}
}

/*GetChartrepoHealthForbidden handles this case with default header values.

Operation is forbidden or quota exceeded
*/
type GetChartrepoHealthForbidden struct {
}

func (o *GetChartrepoHealthForbidden) Error() string {
	return fmt.Sprintf("[GET /chartrepo/health][%d] getChartrepoHealthForbidden ", 403)
}

func (o *GetChartrepoHealthForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetChartrepoHealthOKBody get chartrepo health o k body
swagger:model GetChartrepoHealthOKBody
*/
type GetChartrepoHealthOKBody struct {

	// healthy
	Healthy bool `json:"healthy,omitempty"`
}

// Validate validates this get chartrepo health o k body
func (o *GetChartrepoHealthOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetChartrepoHealthOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetChartrepoHealthOKBody) UnmarshalBinary(b []byte) error {
	var res GetChartrepoHealthOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
