// Code generated by go-swagger; DO NOT EDIT.

package chart_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostChartrepoRepoProvReader is a Reader for the PostChartrepoRepoProv structure.
type PostChartrepoRepoProvReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChartrepoRepoProvReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostChartrepoRepoProvCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostChartrepoRepoProvUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostChartrepoRepoProvForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostChartrepoRepoProvInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 507:
		result := NewPostChartrepoRepoProvInsufficientStorage()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostChartrepoRepoProvCreated creates a PostChartrepoRepoProvCreated with default headers values
func NewPostChartrepoRepoProvCreated() *PostChartrepoRepoProvCreated {
	return &PostChartrepoRepoProvCreated{}
}

/*PostChartrepoRepoProvCreated handles this case with default header values.

The provance file is successfully uploaded.
*/
type PostChartrepoRepoProvCreated struct {
}

func (o *PostChartrepoRepoProvCreated) Error() string {
	return fmt.Sprintf("[POST /chartrepo/{repo}/prov][%d] postChartrepoRepoProvCreated ", 201)
}

func (o *PostChartrepoRepoProvCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostChartrepoRepoProvUnauthorized creates a PostChartrepoRepoProvUnauthorized with default headers values
func NewPostChartrepoRepoProvUnauthorized() *PostChartrepoRepoProvUnauthorized {
	return &PostChartrepoRepoProvUnauthorized{}
}

/*PostChartrepoRepoProvUnauthorized handles this case with default header values.

Unauthorized
*/
type PostChartrepoRepoProvUnauthorized struct {
}

func (o *PostChartrepoRepoProvUnauthorized) Error() string {
	return fmt.Sprintf("[POST /chartrepo/{repo}/prov][%d] postChartrepoRepoProvUnauthorized ", 401)
}

func (o *PostChartrepoRepoProvUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostChartrepoRepoProvForbidden creates a PostChartrepoRepoProvForbidden with default headers values
func NewPostChartrepoRepoProvForbidden() *PostChartrepoRepoProvForbidden {
	return &PostChartrepoRepoProvForbidden{}
}

/*PostChartrepoRepoProvForbidden handles this case with default header values.

Operation is forbidden or quota exceeded
*/
type PostChartrepoRepoProvForbidden struct {
}

func (o *PostChartrepoRepoProvForbidden) Error() string {
	return fmt.Sprintf("[POST /chartrepo/{repo}/prov][%d] postChartrepoRepoProvForbidden ", 403)
}

func (o *PostChartrepoRepoProvForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostChartrepoRepoProvInternalServerError creates a PostChartrepoRepoProvInternalServerError with default headers values
func NewPostChartrepoRepoProvInternalServerError() *PostChartrepoRepoProvInternalServerError {
	return &PostChartrepoRepoProvInternalServerError{}
}

/*PostChartrepoRepoProvInternalServerError handles this case with default header values.

Internal server error occurred
*/
type PostChartrepoRepoProvInternalServerError struct {
}

func (o *PostChartrepoRepoProvInternalServerError) Error() string {
	return fmt.Sprintf("[POST /chartrepo/{repo}/prov][%d] postChartrepoRepoProvInternalServerError ", 500)
}

func (o *PostChartrepoRepoProvInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostChartrepoRepoProvInsufficientStorage creates a PostChartrepoRepoProvInsufficientStorage with default headers values
func NewPostChartrepoRepoProvInsufficientStorage() *PostChartrepoRepoProvInsufficientStorage {
	return &PostChartrepoRepoProvInsufficientStorage{}
}

/*PostChartrepoRepoProvInsufficientStorage handles this case with default header values.

Insufficient storage
*/
type PostChartrepoRepoProvInsufficientStorage struct {
}

func (o *PostChartrepoRepoProvInsufficientStorage) Error() string {
	return fmt.Sprintf("[POST /chartrepo/{repo}/prov][%d] postChartrepoRepoProvInsufficientStorage ", 507)
}

func (o *PostChartrepoRepoProvInsufficientStorage) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
