// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditLogEventType audit log event type
//
// swagger:model AuditLogEventType
type AuditLogEventType struct {

	// the event type, such as create_user.
	// Example: create_user
	EventType string `json:"event_type,omitempty"`
}

// Validate validates this audit log event type
func (m *AuditLogEventType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this audit log event type based on context it is used
func (m *AuditLogEventType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuditLogEventType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditLogEventType) UnmarshalBinary(b []byte) error {
	var res AuditLogEventType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
