// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PayloadFormatType The type of webhook paylod format.
// Example: CloudEvents
//
// swagger:model PayloadFormatType
type PayloadFormatType string

// Validate validates this payload format type
func (m PayloadFormatType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payload format type based on context it is used
func (m PayloadFormatType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
