// Code generated by go-swagger; DO NOT EDIT.

package auditlog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// ListAuditLogExtsReader is a Reader for the ListAuditLogExts structure.
type ListAuditLogExtsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAuditLogExtsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAuditLogExtsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAuditLogExtsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListAuditLogExtsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListAuditLogExtsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAuditLogExtsOK creates a ListAuditLogExtsOK with default headers values
func NewListAuditLogExtsOK() *ListAuditLogExtsOK {
	return &ListAuditLogExtsOK{}
}

/*
ListAuditLogExtsOK describes a response with status code 200, with default header values.

Success
*/
type ListAuditLogExtsOK struct {

	/* Link refers to the previous page and next page
	 */
	Link string

	/* The total count of auditlogs
	 */
	XTotalCount int64

	Payload []*models.AuditLogExt
}

// IsSuccess returns true when this list audit log exts o k response has a 2xx status code
func (o *ListAuditLogExtsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list audit log exts o k response has a 3xx status code
func (o *ListAuditLogExtsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log exts o k response has a 4xx status code
func (o *ListAuditLogExtsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list audit log exts o k response has a 5xx status code
func (o *ListAuditLogExtsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log exts o k response a status code equal to that given
func (o *ListAuditLogExtsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListAuditLogExtsOK) Error() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsOK  %+v", 200, o.Payload)
}

func (o *ListAuditLogExtsOK) String() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsOK  %+v", 200, o.Payload)
}

func (o *ListAuditLogExtsOK) GetPayload() []*models.AuditLogExt {
	return o.Payload
}

func (o *ListAuditLogExtsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := swag.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAuditLogExtsBadRequest creates a ListAuditLogExtsBadRequest with default headers values
func NewListAuditLogExtsBadRequest() *ListAuditLogExtsBadRequest {
	return &ListAuditLogExtsBadRequest{}
}

/*
ListAuditLogExtsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ListAuditLogExtsBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log exts bad request response has a 2xx status code
func (o *ListAuditLogExtsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log exts bad request response has a 3xx status code
func (o *ListAuditLogExtsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log exts bad request response has a 4xx status code
func (o *ListAuditLogExtsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list audit log exts bad request response has a 5xx status code
func (o *ListAuditLogExtsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log exts bad request response a status code equal to that given
func (o *ListAuditLogExtsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListAuditLogExtsBadRequest) Error() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsBadRequest  %+v", 400, o.Payload)
}

func (o *ListAuditLogExtsBadRequest) String() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsBadRequest  %+v", 400, o.Payload)
}

func (o *ListAuditLogExtsBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogExtsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAuditLogExtsUnauthorized creates a ListAuditLogExtsUnauthorized with default headers values
func NewListAuditLogExtsUnauthorized() *ListAuditLogExtsUnauthorized {
	return &ListAuditLogExtsUnauthorized{}
}

/*
ListAuditLogExtsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListAuditLogExtsUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log exts unauthorized response has a 2xx status code
func (o *ListAuditLogExtsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log exts unauthorized response has a 3xx status code
func (o *ListAuditLogExtsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log exts unauthorized response has a 4xx status code
func (o *ListAuditLogExtsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list audit log exts unauthorized response has a 5xx status code
func (o *ListAuditLogExtsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log exts unauthorized response a status code equal to that given
func (o *ListAuditLogExtsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ListAuditLogExtsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsUnauthorized  %+v", 401, o.Payload)
}

func (o *ListAuditLogExtsUnauthorized) String() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsUnauthorized  %+v", 401, o.Payload)
}

func (o *ListAuditLogExtsUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogExtsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAuditLogExtsInternalServerError creates a ListAuditLogExtsInternalServerError with default headers values
func NewListAuditLogExtsInternalServerError() *ListAuditLogExtsInternalServerError {
	return &ListAuditLogExtsInternalServerError{}
}

/*
ListAuditLogExtsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ListAuditLogExtsInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log exts internal server error response has a 2xx status code
func (o *ListAuditLogExtsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log exts internal server error response has a 3xx status code
func (o *ListAuditLogExtsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log exts internal server error response has a 4xx status code
func (o *ListAuditLogExtsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list audit log exts internal server error response has a 5xx status code
func (o *ListAuditLogExtsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list audit log exts internal server error response a status code equal to that given
func (o *ListAuditLogExtsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ListAuditLogExtsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAuditLogExtsInternalServerError) String() string {
	return fmt.Sprintf("[GET /auditlog-exts][%d] listAuditLogExtsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAuditLogExtsInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogExtsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
